### PR TITLE
Brand fix

### PR DESCRIPTION
**Pull request by freethan**
@joecks, @sschuberth 
Fixes https://github.com/heremaps/map-linkbuilder-app/issues/4

### CODE REVIEW

**Comment by sschuberth** [comment]
The changes themselves look good to me, thanks. However, if you want to [auto-close](https://help.github.com/articles/closing-issues-via-commit-messages/) issue #4, the "Fixes #4" needs to go into (of one) the commit messages, not into the PR conversation. This is again a case where I miss that you cannot add review comments to commit messages in GitHub :disappointed:

**Comment by sschuberth** [comment]
@freethan Also, would you mind looking into the timeouts in CI?

**Comment by sschuberth** [comment]
@freethan Just checking, does this also fix the favicon?

**Comment by freethan** [comment]
@sschuberth You're correct. It's now fixed.

**Review by sschuberth — APPROVED** [review]

**Pull request merged**
